---
- hosts: web1
  tasks:
    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true

---
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy Apache welcome file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: reload httpd server
      service:
        name: httpd
        state: reloaded

---
- hosts: all
  gather_facts: no
  tasks:
    - name: Make changes in Apache config
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen 80"
        replace: "Listen 443"
    - name: restart httpd server
      service:
        name: httpd
        state: restarted

---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
