- name: Install Apache2
  apt:
    name: apache2
    state: present
- name: Start Apache2
  service:
    name: apache2
    state: started
    enabled: true
- name: Copy Configuration
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
  notify: restart_httpd

- name: Copy index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html