- name: Install Apache2 in Ubuntu
  include: install-apache2.yml
  when: ansible_distribution == "Ubuntu"

- name: Install Apache2 in CentOS
  include: install-httpd.yml
  when: ansible_distribution == "CentOS"

- name: Copy index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
