---
- name: Install httpd
  hosts: web1
  tasks:
    - name: Install httpd
      yum:
        state: installed
        name: httpd

---
- name: Install wget
  hosts: web1
  tasks:
    - name: Install wget
      yum:
        state: installed
        name: http://mirror.centos.org/centos/7/os/x86_64/Packages/wget-1.14-18.el7_6.1.x86_64.rpm

---
- hosts: all
  tasks:
    - name: Install unzip package
      yum:
        name: unzip-5.52 # specific unzip version
        state: present

---
- hosts: all
  tasks:
    - name: Install latest iotop package
      yum:
        name: iotop
        state: latest

---
- hosts: web1
  tasks:
  - yum: name=sudo state=latest
  - yum: name=vsftpd-2.2.2 state=present allow_downgrade=yes
