FROM centos:7

RUN \
  yum -y install openssh-clients openssh-server sudo && \
  yum -y clean all && \
  touch /run/utmp && \
  echo "root:screencast" | chpasswd

RUN adduser centos && \
    usermod -aG wheel centos && \
    echo 'centos:depi' | chpasswd && \
    echo 'centos     ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# generate host keys if not present
RUN ssh-keygen -A

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
