---
- name: 'Add nameserver in resolv.conf file on localhost'
  hosts: localhost
  become: yes
  tasks:
    - name: 'Add nameserver in resolv.conf file'
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{  nameserver_ip  }}' # this comes from a variable in the inventory file
    - name: 'Disable SNMP Port'
      firewalld:
        port: '{{  snmp_port  }}' # this comes from a variable in the inventory file
        permanent: true
        state: disabled
    
---
- hosts: localhost
  vars:
    car_model: 'BMW'
    country_name: 'USA'
    title: 'Systems Engineer'
  tasks:
    - command: 'echo "My car is {{  car_model  }}"'
    - command: 'echo "I live in the {{  country_name  }}"'
    - command: 'echo "I work as a {{  title  }}"'
