---
- name: Install Apache2
  apt:
    name: apache2
    state: present
- name: Run apache
  service: 
    name: apache2
    state: started
- name: Enable apache2
  service:
    name: apache2
    enabled: true
   