---
- name: Install Vim
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install Vim
      apt:
        name: vim
        state: present
    - include: install_apache2.yml

- name: Install lftp
  import_playbook: second_playbook.yml